-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_name character varying,
  contact_person_name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  address text,
  city character varying,
  province character varying,
  postal_code character varying,
  country character varying DEFAULT 'South Africa'::character varying,
  website_url text,
  industry character varying,
  company_size character varying,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT clients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_submissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  company character varying,
  project_type character varying,
  project_budget_range character varying,
  message text NOT NULL,
  status USER-DEFINED DEFAULT 'new'::contact_status,
  assigned_to uuid,
  follow_up_date date,
  source character varying,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contact_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT contact_submissions_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id)
);
CREATE TABLE public.newsletter_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  name character varying,
  is_active boolean DEFAULT true,
  interests ARRAY,
  subscription_source character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  unsubscribed_at timestamp with time zone,
  CONSTRAINT newsletter_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  slug character varying NOT NULL UNIQUE,
  description text,
  icon_name character varying,
  color_hex character varying,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT project_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL,
  document_name character varying NOT NULL,
  document_url text NOT NULL,
  document_type character varying,
  file_size_bytes bigint,
  mime_type character varying,
  version character varying,
  is_public boolean DEFAULT false,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT project_documents_pkey PRIMARY KEY (id),
  CONSTRAINT project_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT project_documents_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_features (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL,
  feature_name character varying NOT NULL,
  feature_description text,
  feature_category character varying,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT project_features_pkey PRIMARY KEY (id),
  CONSTRAINT project_features_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL,
  image_url text NOT NULL,
  thumbnail_url text,
  alt_text character varying,
  caption text,
  is_featured boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  image_type character varying,
  photographer character varying,
  date_taken date,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT project_images_pkey PRIMARY KEY (id),
  CONSTRAINT project_images_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_team_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL,
  start_date date,
  end_date date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT project_team_members_pkey PRIMARY KEY (id),
  CONSTRAINT project_team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT project_team_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  detailed_description text,
  category_id uuid,
  client_id uuid,
  lead_architect_id uuid,
  location character varying,
  address text,
  latitude numeric,
  longitude numeric,
  total_area_sqm numeric,
  built_area_sqm numeric,
  number_of_floors integer,
  start_date date,
  planned_completion_date date,
  actual_completion_date date,
  design_start_date date,
  construction_start_date date,
  estimated_budget numeric,
  actual_cost numeric,
  currency character varying DEFAULT 'ZAR'::character varying,
  status USER-DEFINED NOT NULL DEFAULT 'planning'::project_status,
  is_featured boolean DEFAULT false,
  is_published boolean DEFAULT false,
  show_on_website boolean DEFAULT true,
  meta_title character varying,
  meta_description text,
  featured_image_url text,
  leed_certification character varying,
  green_star_rating character varying,
  awards ARRAY,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_lead_architect_id_fkey FOREIGN KEY (lead_architect_id) REFERENCES public.users(id),
  CONSTRAINT projects_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.project_categories(id),
  CONSTRAINT projects_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'viewer'::user_role,
  phone character varying,
  title character varying,
  bio text,
  profile_image_url text,
  is_active boolean DEFAULT true,
  years_experience integer,
  specializations ARRAY,
  linkedin_url text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);